print("masukin nama")
#masukkan nama
nama = input ("aditya mahyudi ramadhan")

#masukkan nim
print("masukin nim")
nim = input("2409106101")

#masukkan Harga Gula Sesuai Discount
print("Masukin harga gula")
HARGAGULA = int(input(21000))
HARGADISKONGULAKU = HARGAGULA * 0.07
HARGADISKONMANISKITA = HARGAGULA * 0.11
HARGADISKONGUNUNGMADU = HARGAGULA * 0.13
HARGASESUDAHDISKONGULAKU = HARGAGULA - HARGADISKONGULAKU 
HARGASESUDAHDISKONMANISKITA = HARGAGULA - HARGADISKONMANISKITA
HARGASESUDAHDISKONGUNUNGMADU = HARGAGULA - HARGADISKONGUNUNGMADU

print("HARGA DISKON GULAKU")
print(HARGASESUDAHDISKONGULAKU)
print("HARGA DISKON MANIS KITA")
print(HARGASESUDAHDISKONMANISKITA)
print("HARGA DISKON GUNUNG MADU")
print(HARGASESUDAHDISKONGUNUNGMADU)

